/**
 * Data Retention Types
 *
 * Type definitions for the per-jurisdiction data retention engine.
 * Compliance-critical: supports GDPR, §14b UStG (DE), and other EU fiscal retention laws.
 *
 * @module lib/retention/types
 */

/** Supported entity types subject to retention policies */
export type RetainableEntityType =
  | 'invoice'
  | 'extraction'
  | 'conversion'
  | 'payment'
  | 'user'
  | 'audit_log'
  | 'business_correspondence';

/** ISO 3166-1 alpha-2 country code or special jurisdiction keys */
export type Jurisdiction = 'DE' | 'FR' | 'IT' | 'EU' | 'DEFAULT' | (string & {});

/**
 * A retention policy that binds a jurisdiction + entity type to a legally
 * mandated retention period, including the legal basis for auditability.
 */
export interface RetentionPolicy {
  /** Unique policy identifier */
  readonly id: string;
  /** ISO country code or jurisdiction key (e.g. 'DE', 'EU', 'DEFAULT') */
  readonly jurisdiction: Jurisdiction;
  /** The entity type this policy applies to */
  readonly entityType: RetainableEntityType;
  /** Number of calendar days the entity must be retained */
  readonly retentionDays: number;
  /** Statutory or regulatory basis (e.g. '§14b UStG', 'GDPR Art. 17') */
  readonly legalBasis: string;
  /** Human-readable description of the policy */
  readonly description: string;
}

/** Actions that the retention engine can perform on expired entities */
export type RetentionAction = 'archive' | 'anonymize' | 'delete';

/**
 * A scheduled execution of a retention policy.
 * The engine evaluates these to determine which policies are due.
 */
export interface RetentionSchedule {
  /** References RetentionPolicy.id */
  readonly policyId: string;
  /** The entity type to process */
  readonly entityType: RetainableEntityType;
  /** The action to perform when the retention period expires */
  readonly action: RetentionAction;
  /** ISO-8601 timestamp of the next scheduled run */
  readonly nextRunAt: Date;
}

/**
 * Result summary from a retention engine execution.
 * Used for compliance reporting and audit trails.
 */
export interface RetentionResult {
  /** Total number of entities evaluated */
  readonly processed: number;
  /** Number of entities moved to archive storage */
  readonly archived: number;
  /** Number of entities anonymized (PII replaced with hashes) */
  readonly anonymized: number;
  /** Number of entities permanently deleted */
  readonly deleted: number;
  /** Errors encountered during processing */
  readonly errors: ReadonlyArray<RetentionError>;
}

/** A single error that occurred during retention processing */
export interface RetentionError {
  /** The entity ID that failed */
  readonly entityId: string;
  /** The entity type */
  readonly entityType: RetainableEntityType;
  /** The action that was attempted */
  readonly action: RetentionAction;
  /** Error message */
  readonly message: string;
  /** ISO-8601 timestamp of the failure */
  readonly occurredAt: string;
}

/** Row shape for the retention_policies database table */
export interface RetentionPolicyRow {
  id: string;
  jurisdiction: string;
  entity_type: string;
  retention_days: number;
  legal_basis: string;
  description: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

/** Row shape for the retention_log database table */
export interface RetentionLogRow {
  id: string;
  policy_id: string;
  entity_type: string;
  entity_id: string;
  action: RetentionAction;
  status: 'success' | 'failed';
  error_message: string | null;
  executed_by: string;
  executed_at: string;
}

/**
 * Compliance report generated by the retention engine.
 * Provides a full audit trail for regulatory inspections.
 */
export interface RetentionReport {
  /** ISO-8601 timestamp when the report was generated */
  readonly generatedAt: string;
  /** The reporting period start (ISO-8601) */
  readonly periodStart: string;
  /** The reporting period end (ISO-8601) */
  readonly periodEnd: string;
  /** Policies evaluated during this period */
  readonly policiesEvaluated: number;
  /** Aggregated results per policy */
  readonly results: ReadonlyArray<{
    readonly policyId: string;
    readonly jurisdiction: Jurisdiction;
    readonly entityType: RetainableEntityType;
    readonly result: RetentionResult;
  }>;
  /** Total entities still within retention period */
  readonly entitiesRetained: number;
  /** Total entities processed (archived + anonymized + deleted) */
  readonly entitiesProcessed: number;
}
