/**
 * Phase 2: Structured Outputs JSON Schema
 * Matches ExtractedInvoiceData from types/index.ts.
 * OpenAI requirement: "additionalProperties": false at every object level.
 * No __meta field. Nullable fields use { "type": ["string", "null"] }.
 */

export const EXTRACTION_JSON_SCHEMA = {
  name: 'extracted_invoice_data',
  strict: true,
  schema: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    type: 'object',
    additionalProperties: false,
    required: [
      'invoiceNumber',
      'invoiceDate',
      'buyerName',
      'buyerEmail',
      'buyerAddress',
      'buyerTaxId',
      'sellerName',
      'sellerEmail',
      'sellerAddress',
      'sellerTaxId',
      'lineItems',
      'subtotal',
      'taxAmount',
      'totalAmount',
      'currency',
      'paymentTerms',
      'notes',
    ],
    properties: {
      invoiceNumber: { type: ['string', 'null'] },
      invoiceDate: { type: ['string', 'null'] },
      buyerName: { type: ['string', 'null'] },
      buyerEmail: { type: ['string', 'null'] },
      buyerAddress: { type: ['string', 'null'] },
      buyerCity: { type: ['string', 'null'] },
      buyerPostalCode: { type: ['string', 'null'] },
      buyerCountryCode: { type: ['string', 'null'] },
      buyerTaxId: { type: ['string', 'null'] },
      buyerPhone: { type: ['string', 'null'] },
      buyerVatId: { type: ['string', 'null'] },
      buyerElectronicAddress: { type: ['string', 'null'] },
      buyerElectronicAddressScheme: { type: ['string', 'null'] },
      buyerReference: { type: ['string', 'null'] },
      sellerName: { type: ['string', 'null'] },
      sellerEmail: { type: ['string', 'null'] },
      sellerAddress: { type: ['string', 'null'] },
      sellerCity: { type: ['string', 'null'] },
      sellerPostalCode: { type: ['string', 'null'] },
      sellerCountryCode: { type: ['string', 'null'] },
      sellerTaxId: { type: ['string', 'null'] },
      sellerVatId: { type: ['string', 'null'] },
      sellerTaxNumber: { type: ['string', 'null'] },
      sellerElectronicAddress: { type: ['string', 'null'] },
      sellerElectronicAddressScheme: { type: ['string', 'null'] },
      sellerIban: { type: ['string', 'null'] },
      sellerBic: { type: ['string', 'null'] },
      sellerPhone: { type: ['string', 'null'] },
      sellerContactName: { type: ['string', 'null'] },
      bankName: { type: ['string', 'null'] },
      lineItems: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['description', 'quantity', 'unitPrice', 'totalPrice'],
          properties: {
            description: { type: 'string' },
            quantity: { type: 'number' },
            unitPrice: { type: 'number' },
            totalPrice: { type: 'number' },
            taxRate: { type: ['number', 'null'] },
            taxCategoryCode: { type: ['string', 'null'] },
          },
        },
      },
      subtotal: { type: 'number' },
      taxRate: { type: ['number', 'null'] },
      taxAmount: { type: 'number' },
      totalAmount: { type: 'number' },
      currency: { type: 'string' },
      paymentTerms: { type: ['string', 'null'] },
      notes: { type: ['string', 'null'] },
      confidence: { type: ['number', 'null'] },
      processingTimeMs: { type: ['number', 'null'] },
      documentTypeCode: { type: ['number', 'null'] },
      dueDate: { type: ['string', 'null'] },
      precedingInvoiceReference: { type: ['string', 'null'] },
      prepaidAmount: { type: ['number', 'null'] },
      billingPeriodStart: { type: ['string', 'null'] },
      billingPeriodEnd: { type: ['string', 'null'] },
      allowanceCharges: {
        type: ['array', 'null'],
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['chargeIndicator', 'amount'],
          properties: {
            chargeIndicator: { type: 'boolean' },
            amount: { type: 'number' },
            baseAmount: { type: ['number', 'null'] },
            percentage: { type: ['number', 'null'] },
            reason: { type: ['string', 'null'] },
            reasonCode: { type: ['string', 'null'] },
            taxRate: { type: ['number', 'null'] },
            taxCategoryCode: { type: ['string', 'null'] },
          },
        },
      },
    },
  },
} as const;
