/**
 * Transactional Outbox Types
 *
 * Defines event types, statuses, and data contracts for the outbox pattern.
 * The outbox ensures reliable event publishing by persisting events in the
 * same database transaction as the business operation, then relaying them
 * to BullMQ queues asynchronously.
 *
 * @module lib/outbox/types
 */

// ─── Outbox Event Types ─────────────────────────────────────────────────────

/**
 * Supported domain event types that can be published through the outbox.
 */
export const OUTBOX_EVENT_TYPES = {
  INVOICE_EXTRACTED: 'INVOICE_EXTRACTED',
  INVOICE_CONVERTED: 'INVOICE_CONVERTED',
  CREDITS_DEDUCTED: 'CREDITS_DEDUCTED',
  BATCH_COMPLETED: 'BATCH_COMPLETED',
  USER_CREATED: 'USER_CREATED',
} as const;

export type OutboxEventType = (typeof OUTBOX_EVENT_TYPES)[keyof typeof OUTBOX_EVENT_TYPES];

// ─── Outbox Status ──────────────────────────────────────────────────────────

/**
 * Lifecycle status of an outbox event.
 * - `pending`: Persisted but not yet published to the queue.
 * - `published`: Successfully delivered to BullMQ.
 * - `failed`: Publishing failed after exhausting retries.
 */
export type OutboxStatus = 'pending' | 'published' | 'failed';

// ─── Outbox Event ───────────────────────────────────────────────────────────

/**
 * Domain event stored in the outbox_events table.
 */
export interface OutboxEvent {
  /** UUID primary key. */
  id: string;
  /** The type of aggregate that produced this event (e.g. 'invoice', 'user'). */
  aggregateType: string;
  /** The ID of the aggregate instance (e.g. invoice UUID). */
  aggregateId: string;
  /** The domain event type. */
  eventType: OutboxEventType;
  /** Arbitrary JSON payload for the event. */
  payload: Record<string, unknown>;
  /** Current publishing status. */
  status: OutboxStatus;
  /** When the event was created (ISO 8601). */
  createdAt: string;
  /** When the event was successfully published (ISO 8601 or null). */
  publishedAt: string | null;
  /** Number of publish attempts so far. */
  retryCount: number;
  /** Last error message if publishing failed. */
  lastError: string | null;
}

// ─── Input DTO ──────────────────────────────────────────────────────────────

/**
 * Data required to append a new event to the outbox.
 * The `id`, `status`, `createdAt`, `publishedAt`, `retryCount`, and `lastError`
 * fields are generated by the OutboxService.
 */
export interface AppendOutboxEventInput {
  aggregateType: string;
  aggregateId: string;
  eventType: OutboxEventType;
  payload: Record<string, unknown>;
}

// ─── Database Row (snake_case) ──────────────────────────────────────────────

/**
 * Raw database row shape (snake_case) for the outbox_events table.
 * Used internally for Supabase query results.
 */
export interface OutboxEventRow {
  id: string;
  aggregate_type: string;
  aggregate_id: string;
  event_type: string;
  payload: Record<string, unknown>;
  status: string;
  created_at: string;
  published_at: string | null;
  retry_count: number;
  last_error: string | null;
}
